<Project Sdk="Microsoft.NET.Sdk.Razor">

  <!-- project declaration -->
  <PropertyGroup>
    <AssemblyName>PDP.DREAM.ScribeWebLib</AssemblyName>
    <RootNamespace>PDP.DREAM.ScribeWebLib</RootNamespace>
    <Description>PDP-DREAM ScribeWebLib</Description>
    <IsPackable>true</IsPackable>
    <Platforms>x64;ARM64;AnyCPU;</Platforms>
  </PropertyGroup>

  <!-- dev/test/build/debug configuration -->
  <PropertyGroup>
    <NoWarn>CS1998;CS0103;CS0120;CS0219;CS8032;CS8600;CS8601;CS8602;CS8604;CS8629;CS8669;IDE0047;NU1902;NU1903;</NoWarn>
  </PropertyGroup>

  <!-- required lib references -->
  <ItemGroup>
  </ItemGroup>

  <!-- required PDP references -->
  <ItemGroup>
    <ProjectReference Include="..\PDP.DREAM.NexusWebLib\PDP.DREAM.NexusWebLib.csproj" />
  </ItemGroup>

</Project>

