//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class CiaamNetUserSession {

        public Guid UserGuidRef { get; set; }

        public Guid AppGuidRef { get; set; }

        public DateTime? SessionDateCreated { get; set; }

        public DateTime? SessionDateAccessed { get; set; }

        public DateTime? SessionDateExpired { get; set; }

        public string UserAlias { get; set; }

        public bool UserIsPerson { get; set; }

        public bool UserIsAgent { get; set; }

        public string ConcurrencyStamp { get; set; }

        public virtual CiaamNetUser CiaamNetUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
