//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetRoleClaimConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetRoleClaimConfiguration : IEntityTypeConfiguration<CiaamNetRoleClaim>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetRoleClaim> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetRoleClaim> builder)
        {
            builder.ToTable(@"CiaamNetRoleClaim", @"dbo");
            builder.Property(x => x.ClaimGuidKey).HasColumnName(@"ClaimGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            builder.Property(x => x.RoleGuidRef).HasColumnName(@"RoleGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ClaimType).HasColumnName(@"ClaimType").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.ClaimValue).HasColumnName(@"ClaimValue").HasColumnType(@"nvarchar(1048)").IsRequired().ValueGeneratedNever().HasMaxLength(1048).HasDefaultValueSql(@"''");
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.HasKey(@"ClaimGuidKey");
            builder.HasIndex(@"RoleGuidRef", @"ClaimType").IsUnique(true).HasDatabaseName(@"IX_CiaaNetRoleClaims_RoleGuidRef");
            builder.HasOne(x => x.CiaamNetRole).WithMany(op => op.CiaamNetRoleClaims).HasForeignKey(@"RoleGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetRoleClaim> builder);

        #endregion
    }

}
