//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class QebiUserRole {

        public Guid LinkGuid { get; set; }

        public Guid AppGuid { get; set; }

        public string AppName { get; set; }

        public string AppDescription { get; set; }

        public Guid RoleGuid { get; set; }

        public string RoleName { get; set; }

        public string RoleDescription { get; set; }

        public Guid UserGuid { get; set; }

        public byte RoleCode { get; set; }

        public string UserName { get; set; }

        public string UserAlias { get; set; }

        public bool RoleForQebi { get; set; }

        public bool RoleForNpds { get; set; }

        public bool RoleForAcms { get; set; }

        public string? ConcurrencyStamp { get; set; }

        public virtual QebiUser QebiUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
