//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetUserTokenConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetUserTokenConfiguration : IEntityTypeConfiguration<CiaamNetUserToken>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetUserToken> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetUserToken> builder)
        {
            builder.ToTable(@"CiaamNetUserToken", @"dbo");
            builder.Property(x => x.TokenGuidKey).HasColumnName(@"TokenGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            builder.Property(x => x.LoginProvider).HasColumnName(@"LoginProvider").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType(@"nvarchar(1028)").IsRequired().ValueGeneratedNever().HasMaxLength(1028).HasDefaultValueSql(@"''");
            builder.Property(x => x.UserGuidRef).HasColumnName(@"UserGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.HasKey(@"TokenGuidKey");
            builder.HasIndex(@"LoginProvider", @"Name", @"UserGuidRef").IsUnique(true).HasDatabaseName(@"IX_CiaaNetUserTokens_UserLoginName");
            builder.HasOne(x => x.CiaamNetUser).WithMany(op => op.CiaamNetUserTokens).HasForeignKey(@"UserGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetUserToken> builder);

        #endregion
    }

}
