//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetRoleConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetRoleConfiguration : IEntityTypeConfiguration<CiaamNetRole>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetRole> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetRole> builder)
        {
            builder.ToTable(@"CiaamNetRole", @"dbo");
            builder.Property(x => x.RoleGuidKey).HasColumnName(@"RoleGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            builder.Property(x => x.RoleTypeCodeRef).HasColumnName(@"RoleTypeCodeRef").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.AppGuidRef).HasColumnName(@"AppGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleName).HasColumnName(@"RoleName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.RoleComment).HasColumnName(@"RoleComment").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.HasKey(@"RoleGuidKey");
            builder.HasIndex(@"RoleGuidKey", @"RoleName").IsUnique(true).HasDatabaseName(@"IX_CiaamNetRoles_RoleNameAndGuid");
            builder.HasOne(x => x.CiaamNetApp).WithMany(op => op.CiaamNetRoles).HasForeignKey(@"AppGuidRef").IsRequired(true);
            builder.HasMany(x => x.CiaamNetRoleClaims).WithOne(op => op.CiaamNetRole).HasForeignKey(@"RoleGuidRef").IsRequired(true);
            builder.HasMany(x => x.CiaamNetUserRoleLinks).WithOne(op => op.CiaamNetRole).HasForeignKey(@"RoleGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetRole> builder);

        #endregion
    }

}
