//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class CiaamNetRoleTypeEnum {

        public byte CodeKey { get; set; }

        public string TypeName { get; set; }

        public string TypeDescription { get; set; }

        public bool TypeForQebi { get; set; }

        public bool TypeForNpds { get; set; }

        public bool TypeForAcms { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
