//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetUserClaimConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetUserClaimConfiguration : IEntityTypeConfiguration<CiaamNetUserClaim>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetUserClaim> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetUserClaim> builder)
        {
            builder.ToTable(@"CiaamNetUserClaim", @"dbo");
            builder.Property(x => x.ClaimGuidKey).HasColumnName(@"ClaimGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            builder.Property(x => x.UserGuidRef).HasColumnName(@"UserGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ClaimType).HasColumnName(@"ClaimType").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.ClaimValue).HasColumnName(@"ClaimValue").HasColumnType(@"nvarchar(1024)").IsRequired().ValueGeneratedNever().HasMaxLength(1024).HasDefaultValueSql(@"''");
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.HasKey(@"ClaimGuidKey");
            builder.HasIndex(@"UserGuidRef", @"ClaimType").IsUnique(true).HasDatabaseName(@"IX_UserGuid_ClaimType");
            builder.HasOne(x => x.CiaamNetUser).WithMany(op => op.CiaamNetUserClaims).HasForeignKey(@"UserGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetUserClaim> builder);

        #endregion
    }

}
