//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetRoleTypeEnumConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetRoleTypeEnumConfiguration : IEntityTypeConfiguration<CiaamNetRoleTypeEnum>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetRoleTypeEnum> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetRoleTypeEnum> builder)
        {
            builder.ToTable(@"CiaamNetRoleTypeEnum", @"dbo");
            builder.Property(x => x.CodeKey).HasColumnName(@"CodeKey").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            builder.Property(x => x.TypeName).HasColumnName(@"TypeName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.TypeDescription).HasColumnName(@"TypeDescription").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.TypeForQebi).HasColumnName(@"TypeForQebi").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.TypeForNpds).HasColumnName(@"TypeForNpds").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.TypeForAcms).HasColumnName(@"TypeForAcms").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.HasKey(@"CodeKey");
            builder.HasIndex(@"TypeName").IsUnique(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetRoleTypeEnum> builder);

        #endregion
    }

}
