//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for QebiUserRoleConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class QebiUserRoleConfiguration : IEntityTypeConfiguration<QebiUserRole>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<QebiUserRole> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<QebiUserRole> builder)
        {
            builder.ToTable(@"QebiUserRole", @"dbo");
            builder.Property(x => x.LinkGuid).HasColumnName(@"LinkGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AppGuid).HasColumnName(@"AppGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AppName).HasColumnName(@"AppName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AppDescription).HasColumnName(@"AppDescription").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.RoleGuid).HasColumnName(@"RoleGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleName).HasColumnName(@"RoleName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.RoleDescription).HasColumnName(@"RoleDescription").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.UserGuid).HasColumnName(@"UserGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleCode).HasColumnName(@"RoleCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.UserAlias).HasColumnName(@"UserAlias").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RoleForQebi).HasColumnName(@"RoleForQebi").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleForNpds).HasColumnName(@"RoleForNpds").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RoleForAcms).HasColumnName(@"RoleForAcms").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.HasKey(@"LinkGuid");
            builder.HasOne(x => x.QebiUser).WithMany(op => op.QebiUserRoles).HasForeignKey(@"UserGuid").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<QebiUserRole> builder);

        #endregion
    }

}
