//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for QebiUserSessionConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class QebiUserSessionConfiguration : IEntityTypeConfiguration<QebiUserSession>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<QebiUserSession> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<QebiUserSession> builder)
        {
            builder.ToTable(@"QebiUserSession", @"dbo");
            builder.Property(x => x.UserGuid).HasColumnName(@"UserGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AppGuid).HasColumnName(@"AppGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AppName).HasColumnName(@"AppName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AppDescription).HasColumnName(@"AppDescription").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.UserAlias).HasColumnName(@"UserAlias").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.UserIsPerson).HasColumnName(@"UserIsPerson").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserIsAgent).HasColumnName(@"UserIsAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SessionDateCreated).HasColumnName(@"SessionDateCreated").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.SessionDateAccessed).HasColumnName(@"SessionDateAccessed").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.SessionDateExpired).HasColumnName(@"SessionDateExpired").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.HasKey(@"UserGuid");
            builder.HasOne(x => x.QebiUser).WithMany(op => op.QebiUserSessions).HasForeignKey(@"UserGuid").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<QebiUserSession> builder);

        #endregion
    }

}
