//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class CiaamNetRole {

        /// <summary>
        /// TBD post migration to RoleTypeEnum
        /// </summary>
        public virtual Guid RoleGuidKey { get; set; }

        public byte RoleTypeCodeRef { get; set; }

        public virtual Guid AppGuidRef { get; set; }

        /// <summary>
        /// TBD post migration to RoleTypeEnum
        /// </summary>
        public virtual string RoleName { get; set; }

        public string RoleComment { get; set; }

        public virtual string ConcurrencyStamp { get; set; }

        public virtual CiaamNetApp CiaamNetApp { get; set; }

        public virtual IList<CiaamNetRoleClaim> CiaamNetRoleClaims { get; set; }

        public virtual IList<CiaamNetUserRoleLink> CiaamNetUserRoleLinks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
