//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetUserSessionConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetUserSessionConfiguration : IEntityTypeConfiguration<CiaamNetUserSession>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetUserSession> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetUserSession> builder)
        {
            builder.ToTable(@"CiaamNetUserSession", @"dbo");
            builder.Property(x => x.UserGuidRef).HasColumnName(@"UserGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AppGuidRef).HasColumnName(@"AppGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SessionDateCreated).HasColumnName(@"SessionDateCreated").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.SessionDateAccessed).HasColumnName(@"SessionDateAccessed").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.SessionDateExpired).HasColumnName(@"SessionDateExpired").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.UserAlias).HasColumnName(@"UserAlias").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.UserIsPerson).HasColumnName(@"UserIsPerson").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.UserIsAgent).HasColumnName(@"UserIsAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.HasKey(@"UserGuidRef");
            builder.HasOne(x => x.CiaamNetUser).WithOne(op => op.CiaamNetUserSession).HasForeignKey(typeof(CiaamNetUserSession), @"UserGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetUserSession> builder);

        #endregion
    }

}
