//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CiaamNetUserConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CiaamNetUserConfiguration : IEntityTypeConfiguration<CiaamNetUser>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CiaamNetUser> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CiaamNetUser> builder)
        {
            builder.ToTable(@"CiaamNetUser", @"dbo");
            builder.Property(x => x.UserGuidKey).HasColumnName(@"UserGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            builder.Property(x => x.AppGuidRef).HasColumnName(@"AppGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AccessFailedCount).HasColumnName(@"AccessFailedCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.DateEmailConfirmed).HasColumnName(@"DateEmailConfirmed").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateLastEdit).HasColumnName(@"DateLastEdit").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateLastLockout).HasColumnName(@"DateLastLockout").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateLastLogin).HasColumnName(@"DateLastLogin").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DatePasswordChanged).HasColumnName(@"DatePasswordChanged").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateProfileChanged).HasColumnName(@"DateProfileChanged").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateTokenExpired).HasColumnName(@"DateTokenExpired").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateUserCreated).HasColumnName(@"DateUserCreated").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DateUserNameChanged).HasColumnName(@"DateUserNameChanged").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.EmailAddress).HasColumnName(@"EmailAddress").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.EmailAlternate).HasColumnName(@"EmailAlternate").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.EmailConfirmed).HasColumnName(@"EmailConfirmed").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.LockoutEnabled).HasColumnName(@"LockoutEnabled").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.LockoutEnd).HasColumnName(@"LockoutEnd").HasColumnType(@"datetimeoffset").ValueGeneratedNever();
            builder.Property(x => x.LockoutEndDateUtc).HasColumnName(@"LockoutEndDateUtc").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.Organization).HasColumnName(@"Organization").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128).HasDefaultValueSql(@"''");
            builder.Property(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType(@"nvarchar(1024)").IsRequired().ValueGeneratedNever().HasMaxLength(1024).HasDefaultValueSql(@"''");
            builder.Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.SecurityAnswer).HasColumnName(@"SecurityAnswer").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.SecurityQuestion).HasColumnName(@"SecurityQuestion").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.SecurityStamp).HasColumnName(@"SecurityStamp").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.PhoneAlternate).HasColumnName(@"PhoneAlternate").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.PhoneConfirmed).HasColumnName(@"PhoneConfirmed").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.SecurityToken).HasColumnName(@"SecurityToken").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.TwoFactorEnabled).HasColumnName(@"TwoFactorEnabled").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.UserIsApproved).HasColumnName(@"UserIsApproved").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.AliasIsLocked).HasColumnName(@"AliasIsLocked").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.UserIsAgent).HasColumnName(@"UserIsAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            builder.Property(x => x.UserIsPerson).HasColumnName(@"UserIsPerson").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.UserAlias).HasColumnName(@"UserAlias").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64).HasDefaultValueSql(@"''");
            builder.Property(x => x.WebsiteAddress).HasColumnName(@"WebsiteAddress").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256).HasDefaultValueSql(@"''");
            builder.HasKey(@"UserGuidKey");
            builder.HasIndex(@"UserName").IsUnique(true);
            builder.HasIndex(@"UserAlias").IsUnique(true);
            builder.HasMany(x => x.CiaamNetUserClaims).WithOne(op => op.CiaamNetUser).HasForeignKey(@"UserGuidRef").IsRequired(true);
            builder.HasMany(x => x.CiaamNetUserLogins).WithOne(op => op.CiaamNetUser).HasForeignKey(@"UserGuidRef").IsRequired(true);
            builder.HasMany(x => x.CiaamNetUserRoleLinks).WithOne(op => op.CiaamNetUser).HasForeignKey(@"UserGuidRef").IsRequired(true);
            builder.HasOne(x => x.CiaamNetUserSession).WithOne(op => op.CiaamNetUser).HasForeignKey(typeof(CiaamNetUserSession), @"UserGuidRef").IsRequired(false);
            builder.HasMany(x => x.CiaamNetUserTokens).WithOne(op => op.CiaamNetUser).HasForeignKey(@"UserGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CiaamNetUser> builder);

        #endregion
    }

}
