//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/28/2024 11:24:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class CiaamNetUser {

        public Guid UserGuidKey { get; set; }

        public Guid AppGuidRef { get; set; }

        public int AccessFailedCount { get; set; }

        public string ConcurrencyStamp { get; set; }

        public DateTime? DateEmailConfirmed { get; set; }

        public DateTime? DateLastEdit { get; set; }

        public DateTime? DateLastLockout { get; set; }

        public DateTime? DateLastLogin { get; set; }

        public DateTime? DatePasswordChanged { get; set; }

        public DateTime? DateProfileChanged { get; set; }

        public DateTime? DateTokenExpired { get; set; }

        public DateTime? DateUserCreated { get; set; }

        public DateTime? DateUserNameChanged { get; set; }

        public string EmailAddress { get; set; }

        public string EmailAlternate { get; set; }

        public bool EmailConfirmed { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public bool LockoutEnabled { get; set; }

        public DateTimeOffset? LockoutEnd { get; set; }

        public DateTime? LockoutEndDateUtc { get; set; }

        public string Organization { get; set; }

        public string PasswordHash { get; set; }

        public string PhoneNumber { get; set; }

        public string SecurityAnswer { get; set; }

        public string SecurityQuestion { get; set; }

        public string SecurityStamp { get; set; }

        public string PhoneAlternate { get; set; }

        public bool PhoneConfirmed { get; set; }

        public string SecurityToken { get; set; }

        public bool TwoFactorEnabled { get; set; }

        public bool UserIsApproved { get; set; }

        public bool AliasIsLocked { get; set; }

        public bool UserIsAgent { get; set; }

        public bool UserIsPerson { get; set; }

        public string UserName { get; set; }

        public string UserAlias { get; set; }

        public string WebsiteAddress { get; set; }

        public virtual IList<CiaamNetUserClaim> CiaamNetUserClaims { get; set; }

        public virtual IList<CiaamNetUserLogin> CiaamNetUserLogins { get; set; }

        public virtual IList<CiaamNetUserRoleLink> CiaamNetUserRoleLinks { get; set; }

        public virtual CiaamNetUserSession CiaamNetUserSession { get; set; }

        public virtual IList<CiaamNetUserToken> CiaamNetUserTokens { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
