//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021-06-07 21:18:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.NpdsDataLib.Stores.NpdsSqlDatabase
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class NexusServiceRestrictionAnd {

        public NexusServiceRestrictionAnd()
        {
            this.NexusServiceRestrictionOrs = new List<NexusServiceRestrictionOr>();
            OnCreated();
        }

        public virtual Guid RestrictionAndGuidKey { get; set; }

        public virtual string? ServiceName { get; set; }

        public virtual Guid InfosetGuidRef { get; set; }

        public virtual Guid RecordGuidRef { get; set; }

        public virtual string ServiceLabel { get; set; }

        public virtual Guid AuditGuidRef { get; set; }

        public virtual string RestrictionName { get; set; }

        public virtual byte HasIndex { get; set; }

        public virtual byte HasPriority { get; set; }

        public virtual bool IsSufficient { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual DateTime? CreatedOn { get; set; }

        public virtual Guid? CreatedByAgentGuid { get; set; }

        public virtual DateTime? UpdatedOn { get; set; }

        public virtual Guid? UpdatedByAgentGuid { get; set; }

        public virtual DateTime? DeletedOn { get; set; }

        public virtual Guid? DeletedByAgentGuid { get; set; }

        public virtual IList<NexusServiceRestrictionOr> NexusServiceRestrictionOrs { get; set; }

        public virtual NexusResrepStem NexusResrepStem { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
