//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021-06-07 21:18:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.NpdsDataLib.Stores.NpdsSqlDatabase
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class NexusResrepRoot {

        public NexusResrepRoot()
        {
            this.NexusEntityLabels = new List<NexusEntityLabel>();
            this.NexusSupportingTags = new List<NexusSupportingTag>();
            this.NexusSupportingLabels = new List<NexusSupportingLabel>();
            this.NexusCrossReferences = new List<NexusCrossReference>();
            this.NexusOtherTexts = new List<NexusOtherText>();
            this.NexusLocations = new List<NexusLocation>();
            this.NexusDescriptions = new List<NexusDescription>();
            this.NexusProvenances = new List<NexusProvenance>();
            this.NexusDistributions = new List<NexusDistribution>();
            this.NexusFairMetrics = new List<NexusFairMetric>();
            this.NexusEntityCanonicalLabels = new List<NexusEntityCanonicalLabel>();
            this.NexusEntityAliasLabels = new List<NexusEntityAliasLabel>();
            OnCreated();
        }

        public virtual Guid RecordGuidKey { get; set; }

        public virtual short EntityTypeCodeRef { get; set; }

        public virtual string EntityTypeName { get; set; }

        public virtual bool EntityTypeIsComponent { get; set; }

        public virtual bool EntityTypeIsConstituent { get; set; }

        public virtual bool EntityTypeEditedByAuthor { get; set; }

        public virtual bool EntityTypeEditedByEditor { get; set; }

        public virtual bool EntityTypeEditedByAdmin { get; set; }

        public virtual string? EntityInitialTag { get; set; }

        public virtual string? EntityName { get; set; }

        public virtual string? EntityNature { get; set; }

        public virtual string? RecordHandle { get; set; }

        public virtual bool RecordIsDeleted { get; set; }

        public virtual bool RecordIsCached { get; set; }

        public virtual Guid RecordDiristryGuidRef { get; set; }

        public virtual string? RecordDiristryTag { get; set; }

        public virtual Guid RecordRegistryGuidRef { get; set; }

        public virtual string? RecordRegistryTag { get; set; }

        public virtual Guid RecordDirectoryGuidRef { get; set; }

        public virtual string? RecordDirectoryTag { get; set; }

        public virtual DateTime? RecordCreatedOn { get; set; }

        public virtual string? RecordRegistrarTag { get; set; }

        public virtual DateTime? RecordUpdatedOn { get; set; }

        public virtual Guid RecordRegistrarGuidRef { get; set; }

        public virtual DateTime? RecordDeletedOn { get; set; }

        public virtual Guid? RecordCreatedByAgentGuidRef { get; set; }

        public virtual Guid? RecordUpdatedByAgentGuidRef { get; set; }

        public virtual Guid? RecordDeletedByAgentGuidRef { get; set; }

        public virtual Guid? RecordManagedByAgentGuidRef { get; set; }

        public virtual Guid InfosetGuidKey { get; set; }

        public virtual bool InfosetIsAuthorPrivate { get; set; }

        public virtual bool InfosetIsAgentShared { get; set; }

        public virtual bool InfosetIsUpdaterLimited { get; set; }

        public virtual bool InfosetIsManagerReleased { get; set; }

        public virtual IList<NexusEntityLabel> NexusEntityLabels { get; set; }

        public virtual IList<NexusSupportingTag> NexusSupportingTags { get; set; }

        public virtual IList<NexusSupportingLabel> NexusSupportingLabels { get; set; }

        public virtual IList<NexusCrossReference> NexusCrossReferences { get; set; }

        public virtual IList<NexusOtherText> NexusOtherTexts { get; set; }

        public virtual IList<NexusLocation> NexusLocations { get; set; }

        public virtual IList<NexusDescription> NexusDescriptions { get; set; }

        public virtual IList<NexusProvenance> NexusProvenances { get; set; }

        public virtual IList<NexusDistribution> NexusDistributions { get; set; }

        public virtual IList<NexusFairMetric> NexusFairMetrics { get; set; }

        public virtual IList<NexusEntityCanonicalLabel> NexusEntityCanonicalLabels { get; set; }

        public virtual IList<NexusEntityAliasLabel> NexusEntityAliasLabels { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
