//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/26/2022 6:00:30 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CoreServiceRestrictionOrConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class CoreServiceRestrictionOrConfiguration : IEntityTypeConfiguration<CoreServiceRestrictionOr>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CoreServiceRestrictionOr> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CoreServiceRestrictionOr> builder)
        {
            builder.HasNoKey();
            builder.ToView(@"CoreServiceRestrictionOr", @"dbo");
            builder.Property(x => x.ServiceName).HasColumnName(@"ServiceName").HasColumnType(@"nvarchar(128)").ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.ServiceLabel).HasColumnName(@"ServiceLabel").HasColumnType(@"nvarchar(384)").IsRequired().ValueGeneratedNever().HasMaxLength(384);
            builder.Property(x => x.RecordGuidRef).HasColumnName(@"RecordGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetGuidRef).HasColumnName(@"InfosetGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RestrictionAndGuidRef).HasColumnName(@"RestrictionAndGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AndAuditGuidRef).HasColumnName(@"AndAuditGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AndHasIndex).HasColumnName(@"AndHasIndex").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            builder.Property(x => x.RestrictionName).HasColumnName(@"RestrictionName").HasColumnType(@"nvarchar(128)").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.RestrictionOrGuidKey).HasColumnName(@"RestrictionOrGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.OrAuditGuidRef).HasColumnName(@"OrAuditGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.OrHasIndex).HasColumnName(@"OrHasIndex").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            builder.Property(x => x.RestrictionValue).HasColumnName(@"RestrictionValue").HasColumnType(@"nvarchar(384)").IsRequired().ValueGeneratedNever().HasMaxLength(384);
            builder.Property(x => x.IsWordPhrase).HasColumnName(@"IsWordPhrase").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsConceptLabel).HasColumnName(@"IsConceptLabel").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.CreatedByAgentGuid).HasColumnName(@"CreatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.UpdatedByAgentGuid).HasColumnName(@"UpdatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.DeletedOn).HasColumnName(@"DeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DeletedByAgentGuid).HasColumnName(@"DeletedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CoreServiceRestrictionOr> builder);

        #endregion
    }

}
