<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <ItemGroup>
    <AssemblyAttribute Include="PDP.DREAM.CoreDataLib.Types.PdpCodeDateAttribute">
      <_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
      <_Parameter1_TypeName>System.String</_Parameter1_TypeName>
    </AssemblyAttribute>
  </ItemGroup>
  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <Authors>Carl Taswell and the PORTAL-DOORS Project Team</Authors>
    <Company>Brain Health Alliance</Company>
    <Copyright>
      PORTAL-DOORS Project Copyright © 2006-$([System.DateTime]::UtcNow.Year) Brain Health Alliance.
      All rights reserved. Code assembly built $([System.DateTime]::UtcNow.ToString("s"))
    </Copyright>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Deterministic>false</Deterministic>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>x64;ARM64;</Platforms>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <RunAnalyzers>false</RunAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
</Project>