//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class DoorsLocationExtn {

        public Guid FgroupGuid { get; set; }

        public Guid RecordGuid { get; set; }

        public string Location { get; set; }

        public byte FieldFormatCode { get; set; }

        public string FieldFormatName { get; set; }

        public byte InfosetTypeCode { get; set; }

        public string InfosetTypeName { get; set; }

        public byte HasIndex { get; set; }

        public byte HasPriority { get; set; }

        public bool IsDeleted { get; set; }

        public bool IsMarked { get; set; }

        public bool IsPrincipal { get; set; }

        public string DisplayText { get; set; }

        public string DisplayImageUrl { get; set; }

        public string UrlWebAddress { get; set; }

        public DateTime? UrlWebAddressValidated { get; set; }

        public string EmailAddress { get; set; }

        public DateTime? EmailAddressValidated { get; set; }

        public string StreetAddress { get; set; }

        public DateTime? StreetAddressValidated { get; set; }

        public string ExtendedAddress { get; set; }

        public string FormattedAddress { get; set; }

        public string CityLocality { get; set; }

        public string StateRegion { get; set; }

        public string Country { get; set; }

        public string PostalCode { get; set; }

        public string Telephone { get; set; }

        public string GeocodeType { get; set; }

        public string GeocodeConfidence { get; set; }

        public double Latitude { get; set; }

        public double Longitude { get; set; }

        public Guid? ManagedByAgentGuid { get; set; }

        public string? ManagedByAgentAlias { get; set; }

        public Guid? AuthoredByAgentGuid { get; set; }

        public string? AuthoredByAgentAlias { get; set; }

        public Guid? ReviewedByAgentGuid { get; set; }

        public string? ReviewedByAgentAlias { get; set; }

        public Guid? EditedByAgentGuid { get; set; }

        public string? EditedByAgentAlias { get; set; }

        public DateTime? CreatedOn { get; set; }

        public Guid? CreatedByAgentGuid { get; set; }

        public string? CreatedByAgentAlias { get; set; }

        public DateTime? UpdatedOn { get; set; }

        public Guid? UpdatedByAgentGuid { get; set; }

        public string? UpdatedByAgentAlias { get; set; }

        public DateTime? DeletedOn { get; set; }

        public Guid? DeletedByAgentGuid { get; set; }

        public string? DeletedByAgentAlias { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
