//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CoreAccessConnectConfiguration in the schema.
    /// </summary>
    public partial class CoreAccessConnectConfiguration : IEntityTypeConfiguration<CoreAccessConnect>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CoreAccessConnect> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CoreAccessConnect> builder)
        {
            builder.ToTable(@"CoreAccessConnect", @"dbo");
            builder.Property(x => x.AccessGuid).HasColumnName(@"AccessGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordGuid).HasColumnName(@"RecordGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AgentGuid).HasColumnName(@"AgentGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AuthorHasResrepAccess).HasColumnName(@"AuthorHasResrepAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AuthorHasServiceAccess).HasColumnName(@"AuthorHasServiceAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ReviewerHasResrepAccess).HasColumnName(@"ReviewerHasResrepAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ReviewerHasServiceAccess).HasColumnName(@"ReviewerHasServiceAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EditorHasResrepAccess).HasColumnName(@"EditorHasResrepAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EditorHasServiceAccess).HasColumnName(@"EditorHasServiceAccess").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"AccessGuid");

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CoreAccessConnect> builder);

        #endregion
    }

}
