//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreAccessConnect {

        public Guid AccessGuid { get; set; }

        public Guid RecordGuid { get; set; }

        public Guid AgentGuid { get; set; }

        public bool AuthorHasResrepAccess { get; set; }

        public bool AuthorHasServiceAccess { get; set; }

        public bool ReviewerHasResrepAccess { get; set; }

        public bool ReviewerHasServiceAccess { get; set; }

        public bool EditorHasResrepAccess { get; set; }

        public bool EditorHasServiceAccess { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
