//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreResrepLeaf {

        public Guid RecordGuid { get; set; }

        public short EntityTypeCode { get; set; }

        public string EntityTypeName { get; set; }

        public bool EntityTypeIsComponent { get; set; }

        public bool EntityTypeIsConstituent { get; set; }

        public bool EntityTypeEditedByAgent { get; set; }

        public bool EntityTypeEditedByReviewer { get; set; }

        public bool EntityTypeEditedByAuthor { get; set; }

        public bool EntityTypeEditedByEditor { get; set; }

        public bool EntityTypeEditedByAdmin { get; set; }

        public string EntityInitialPrincipalTag { get; set; }

        public string EntityInitialSupportingTag { get; set; }

        public string EntityName { get; set; }

        public string EntityNature { get; set; }

        public Guid? EntityOtherGuid { get; set; }

        public string EntityPrincipalTag { get; set; }

        public string EntityCanonicalLabel { get; set; }

        public Guid? EntityOwnerGuid { get; set; }

        public string? EntityOtherName { get; set; }

        public string? EntityOtherTag { get; set; }

        public string? EntityOtherLabel { get; set; }

        public Guid? EntityContactGuid { get; set; }

        public string? EntityOwnerName { get; set; }

        public string? EntityOwnerTag { get; set; }

        public Guid? RecordRegistrantGuid { get; set; }

        public string? EntityOwnerLabel { get; set; }

        public string? EntityContactName { get; set; }

        public string? EntityContactTag { get; set; }

        public string? EntityContactLabel { get; set; }

        public string? RecordRegistrantName { get; set; }

        public string? RecordRegistrantTag { get; set; }

        public string? RecordRegistrantLabel { get; set; }

        public Guid RecordDiristryGuid { get; set; }

        public string RecordHandle { get; set; }

        public string? RecordSignature { get; set; }

        public Guid RecordRegistryGuid { get; set; }

        public Guid RecordDirectoryGuid { get; set; }

        public string RecordDiristryName { get; set; }

        public string RecordDiristryTag { get; set; }

        public Guid RecordRegistrarGuid { get; set; }

        public string RecordDiristryLabel { get; set; }

        public string RecordRegistryName { get; set; }

        public DateTime? RecordCachedOn { get; set; }

        public Guid? RecordCachedByAgentGuid { get; set; }

        public string? RecordCachedByAgentAlias { get; set; }

        public DateTime? RecordCreatedOn { get; set; }

        public Guid? RecordCreatedByAgentGuid { get; set; }

        public string RecordRegistryTag { get; set; }

        public string? RecordCreatedByAgentAlias { get; set; }

        public string RecordRegistryLabel { get; set; }

        public Guid? RecordArchivedByAgentGuid { get; set; }

        public DateTime? RecordDeletedOn { get; set; }

        public string? RecordArchivedByAgentAlias { get; set; }

        public Guid? RecordDeletedByAgentGuid { get; set; }

        public Guid? RecordEditedByAgentGuid { get; set; }

        public string? RecordEditedByAgentAlias { get; set; }

        public string? RecordDeletedByAgentAlias { get; set; }

        public Guid? RecordManagedByAgentGuid { get; set; }

        public string? RecordManagedByAgentAlias { get; set; }

        public Guid? RecordAuthoredByAgentGuid { get; set; }

        public bool RecordIsCached { get; set; }

        public string? RecordAuthoredByAgentAlias { get; set; }

        public DateTime? RecordUpdatedOn { get; set; }

        public Guid? RecordReviewedByAgentGuid { get; set; }

        public string? RecordReviewedByAgentAlias { get; set; }

        public Guid? RecordUpdatedByAgentGuid { get; set; }

        public string? RecordUpdatedByAgentAlias { get; set; }

        public bool RecordIsDeleted { get; set; }

        public string RecordDirectoryName { get; set; }

        public string RecordDirectoryTag { get; set; }

        public string RecordDirectoryLabel { get; set; }

        public string RecordRegistrarName { get; set; }

        public string RecordRegistrarTag { get; set; }

        public string RecordRegistrarLabel { get; set; }

        public Guid InfosetGuid { get; set; }

        public string? InfosetEntailment { get; set; }

        public bool InfosetIsAuthorPrivate { get; set; }

        public bool InfosetIsAgentShared { get; set; }

        public bool InfosetIsUpdaterLimited { get; set; }

        public bool InfosetIsManagerReleased { get; set; }

        public DateTime? InfosetPortalStatusTestedOn { get; set; }

        public short InfosetPortalStatusCode { get; set; }

        public string? InfosetPortalStatusName { get; set; }

        public DateTime? InfosetDoorsStatusTestedOn { get; set; }

        public short InfosetDoorsStatusCode { get; set; }

        public string? InfosetDoorsStatusName { get; set; }

        public DateTime? InfosetResrepEntityTestedOn { get; set; }

        public short InfosetResrepEntityStatusCode { get; set; }

        public string? InfosetResrepEntityStatusName { get; set; }

        public DateTime? InfosetResrepRecordTestedOn { get; set; }

        public short InfosetResrepRecordStatusCode { get; set; }

        public string? InfosetResrepRecordStatusName { get; set; }

        public DateTime? InfosetResrepInfosetTestedOn { get; set; }

        public short InfosetResrepInfosetStatusCode { get; set; }

        public string? InfosetResrepInfosetStatusName { get; set; }

        public int InfosetEntityLabelsCount { get; set; }

        public short InfosetEntityLabelsStatusCode { get; set; }

        public string? InfosetEntityLabelsStatusName { get; set; }

        public int InfosetSupportingTagsCount { get; set; }

        public short InfosetSupportingTagsStatusCode { get; set; }

        public string? InfosetSupportingTagsStatusName { get; set; }

        public int InfosetSupportingLabelsCount { get; set; }

        public short InfosetSupportingLabelsStatusCode { get; set; }

        public string? InfosetSupportingLabelsStatusName { get; set; }

        public int InfosetCrossReferencesCount { get; set; }

        public short InfosetCrossReferencesStatusCode { get; set; }

        public string? InfosetCrossReferencesStatusName { get; set; }

        public int InfosetOtherTextsCount { get; set; }

        public short InfosetOtherTextsStatusCode { get; set; }

        public string? InfosetOtherTextsStatusName { get; set; }

        public int InfosetLocationsCount { get; set; }

        public short InfosetLocationsStatusCode { get; set; }

        public string? InfosetLocationsStatusName { get; set; }

        public int InfosetDescriptionsCount { get; set; }

        public short InfosetDescriptionsStatusCode { get; set; }

        public string? InfosetDescriptionsStatusName { get; set; }

        public int InfosetProvenancesCount { get; set; }

        public short InfosetProvenancesStatusCode { get; set; }

        public string? InfosetProvenancesStatusName { get; set; }

        public int InfosetDistributionsCount { get; set; }

        public short InfosetDistributionsStatusCode { get; set; }

        public string? InfosetDistributionsStatusName { get; set; }

        public int InfosetFairMetricsCount { get; set; }

        public short InfosetFairMetricsStatusCode { get; set; }

        public string? InfosetFairMetricsStatusName { get; set; }

        public int InfosetNexusSnapshotsCount { get; set; }

        public short InfosetNexusSnapshotsStatusCode { get; set; }

        public string? InfosetNexusSnapshotsStatusName { get; set; }

        public virtual IList<CoreEntityLabel> CoreEntityLabels { get; set; }

        public virtual IList<CoreEntityAliasLabel> CoreEntityAliasLabels { get; set; }

        public virtual IList<CoreEntityCanonicalLabel> CoreEntityCanonicalLabels { get; set; }

        public virtual IList<PortalSupportingTag> PortalSupportingTags { get; set; }

        public virtual IList<PortalSupportingLabel> PortalSupportingLabels { get; set; }

        public virtual IList<PortalCrossReference> PortalCrossReferences { get; set; }

        public virtual IList<PortalOtherText> PortalOtherTexts { get; set; }

        public virtual IList<DoorsLocation> DoorsLocations { get; set; }

        public virtual IList<DoorsDescription> DoorsDescriptions { get; set; }

        public virtual IList<DoorsProvenance> DoorsProvenances { get; set; }

        public virtual IList<DoorsDistribution> DoorsDistributions { get; set; }

        public virtual IList<DoorsFairMetric> DoorsFairMetrics { get; set; }

        public virtual IList<CoreServiceRestrictionAnd> CoreServiceRestrictionAnds { get; set; }

        public virtual IList<CoreResrepService> CoreResrepServices { get; set; }

        public virtual IList<CoreResrepSnapshot> CoreResrepSnapshots { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
