//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for DoorsLocationConfiguration in the schema.
    /// </summary>
    public partial class DoorsLocationConfiguration : IEntityTypeConfiguration<DoorsLocation>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<DoorsLocation> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<DoorsLocation> builder)
        {
            builder.ToTable(@"DoorsLocation", @"dbo");
            builder.Property(x => x.FgroupGuid).HasColumnName(@"FgroupGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordGuid).HasColumnName(@"RecordGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetTypeCode).HasColumnName(@"InfosetTypeCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetTypeName).HasColumnName(@"InfosetTypeName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.FieldFormatCode).HasColumnName(@"FieldFormatCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.FieldFormatName).HasColumnName(@"FieldFormatName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Location).HasColumnName(@"Location").HasColumnType(@"nvarchar(max)").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.HasIndex).HasColumnName(@"HasIndex").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.HasPriority).HasColumnName(@"HasPriority").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.ManagedByAgentGuid).HasColumnName(@"ManagedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.ManagedByAgentAlias).HasColumnName(@"ManagedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AuthoredByAgentGuid).HasColumnName(@"AuthoredByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.AuthoredByAgentAlias).HasColumnName(@"AuthoredByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.ReviewedByAgentGuid).HasColumnName(@"ReviewedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EditedByAgentGuid).HasColumnName(@"EditedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EditedByAgentAlias).HasColumnName(@"EditedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.IsMarked).HasColumnName(@"IsMarked").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ReviewedByAgentAlias).HasColumnName(@"ReviewedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.CreatedByAgentGuid).HasColumnName(@"CreatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.CreatedByAgentAlias).HasColumnName(@"CreatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.IsPrincipal).HasColumnName(@"IsPrincipal").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UpdatedByAgentGuid).HasColumnName(@"UpdatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.UpdatedByAgentAlias).HasColumnName(@"UpdatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DeletedByAgentGuid).HasColumnName(@"DeletedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.DeletedByAgentAlias).HasColumnName(@"DeletedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DeletedOn).HasColumnName(@"DeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.HasKey(@"FgroupGuid");
            builder.HasOne(x => x.CoreResrepLeaf).WithMany(op => op.DoorsLocations).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasOne(x => x.CoreResrepRoot).WithMany(op => op.DoorsLocations).HasForeignKey(@"RecordGuid").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<DoorsLocation> builder);

        #endregion
    }

}
