//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CoreAccessAuditConfiguration in the schema.
    /// </summary>
    public partial class CoreAccessAuditConfiguration : IEntityTypeConfiguration<CoreAccessAudit>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CoreAccessAudit> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CoreAccessAudit> builder)
        {
            builder.ToTable(@"CoreAccessAudit", @"dbo");
            builder.Property(x => x.FgroupGuid).HasColumnName(@"FgroupGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.HasVersion).HasColumnName(@"HasVersion").HasColumnType(@"timestamp").IsRequired().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.RecordHandle).HasColumnName(@"RecordHandle").HasColumnType(@"nchar(9)").IsRequired().ValueGeneratedNever().HasMaxLength(9);
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordGuid).HasColumnName(@"RecordGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetGuid).HasColumnName(@"InfosetGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AuthoredByAgentGuid).HasColumnName(@"AuthoredByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.AuthoredByAgentAlias).HasColumnName(@"AuthoredByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.ReviewedByAgentGuid).HasColumnName(@"ReviewedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.ReviewedByAgentAlias).HasColumnName(@"ReviewedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EditedByAgentGuid).HasColumnName(@"EditedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EditedByAgentAlias).HasColumnName(@"EditedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.ManagedByAgentGuid).HasColumnName(@"ManagedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RequestedForAgentGuid).HasColumnName(@"RequestedForAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RequestedForAgentAlias).HasColumnName(@"RequestedForAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AllowedByAgentGuid).HasColumnName(@"AllowedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.AllowedByAgentAlias).HasColumnName(@"AllowedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.DeniedByAgentGuid).HasColumnName(@"DeniedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.DeniedByAgentAlias).HasColumnName(@"DeniedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AccessAsAuthor).HasColumnName(@"AccessAsAuthor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AccessAsReviewer).HasColumnName(@"AccessAsReviewer").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AccessAsEditor).HasColumnName(@"AccessAsEditor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AccessForService).HasColumnName(@"AccessForService").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ManagedByAgentAlias).HasColumnName(@"ManagedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.AccessIsAllowed).HasColumnName(@"AccessIsAllowed").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AccessIsDenied).HasColumnName(@"AccessIsDenied").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.AuthorHasResrepAccess).HasColumnName(@"AuthorHasResrepAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.ReviewerHasResrepAccess).HasColumnName(@"ReviewerHasResrepAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.EditorHasResrepAccess).HasColumnName(@"EditorHasResrepAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.AuthorHasServiceAccess).HasColumnName(@"AuthorHasServiceAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.ReviewerHasServiceAccess).HasColumnName(@"ReviewerHasServiceAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.EditorHasServiceAccess).HasColumnName(@"EditorHasServiceAccess").HasColumnType(@"bit").ValueGeneratedNever();
            builder.Property(x => x.HasIndex).HasColumnName(@"HasIndex").HasColumnType(@"tinyint").ValueGeneratedNever().HasPrecision(3, 0);
            builder.Property(x => x.HasPriority).HasColumnName(@"HasPriority").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.IsAllowed).HasColumnName(@"IsAllowed").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsArchived).HasColumnName(@"IsArchived").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsCached).HasColumnName(@"IsCached").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsConceptLabel).HasColumnName(@"IsConceptLabel").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsConcise).HasColumnName(@"IsConcise").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsDenied).HasColumnName(@"IsDenied").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsExcluding).HasColumnName(@"IsExcluding").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsGenerating).HasColumnName(@"IsGenerating").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsLimited).HasColumnName(@"IsLimited").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsMarked).HasColumnName(@"IsMarked").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsResolvable).HasColumnName(@"IsResolvable").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsPrincipal).HasColumnName(@"IsPrincipal").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsPrivate).HasColumnName(@"IsPrivate").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsSufficient).HasColumnName(@"IsSufficient").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsWordPhrase).HasColumnName(@"IsWordPhrase").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.CreatedByAgentGuid).HasColumnName(@"CreatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.CreatedByAgentAlias).HasColumnName(@"CreatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.UpdatedByAgentGuid).HasColumnName(@"UpdatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.UpdatedByAgentAlias).HasColumnName(@"UpdatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.DeletedOn).HasColumnName(@"DeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.DeletedByAgentGuid).HasColumnName(@"DeletedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.DeletedByAgentAlias).HasColumnName(@"DeletedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.HasKey(@"FgroupGuid");

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CoreAccessAudit> builder);

        #endregion
    }

}
