//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreEntityTypeItem {

        public virtual byte CodeKey { get; set; }

        public virtual string TypeName { get; set; }

        public virtual string TypeDescription { get; set; }

        public virtual bool TypeIsComponent { get; set; }

        public virtual bool TypeIsConstituent { get; set; }

        public virtual bool TypeEditedByAgent { get; set; }

        public virtual bool TypeEditedByAuthor { get; set; }

        public bool TypeEditedByReviewer { get; set; }

        public virtual bool TypeEditedByEditor { get; set; }

        public virtual bool TypeEditedByAdmin { get; set; }

        public virtual CoreResrepRoot CoreResrepRoot { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
