//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreServiceRestrictionAnd {

        public virtual Guid RestrictionAndGuidKey { get; set; }

        public virtual string ServiceName { get; set; }

        public virtual string ServiceLabel { get; set; }

        public virtual Guid ServiceIGuid { get; set; }

        public Guid InfosetGuid { get; set; }

        public virtual Guid ServiceRGuid { get; set; }

        public byte AndHasIndex { get; set; }

        public byte AndHasPriority { get; set; }

        public virtual string RestrictionName { get; set; }

        public virtual bool IsExcluding { get; set; }

        public virtual bool IsSufficient { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual DateTime? CreatedOn { get; set; }

        public virtual Guid? CreatedByAgentGuid { get; set; }

        public virtual DateTime? UpdatedOn { get; set; }

        public virtual Guid? UpdatedByAgentGuid { get; set; }

        public virtual DateTime? DeletedOn { get; set; }

        public virtual Guid? DeletedByAgentGuid { get; set; }

        public Guid RecordGuid { get; set; }

        public virtual CoreResrepLeaf CoreResrepLeaf { get; set; }

        public virtual CoreResrepRoot CoreResrepRoot { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
