//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreEntityCanonicalLabel {

        public Guid FgroupGuid { get; set; }

        public Guid InfosetGuid { get; set; }

        public Guid RecordGuid { get; set; }

        public byte ServiceTypeCode { get; set; }

        public byte InfosetTypeCode { get; set; }

        public byte EntityTypeCode { get; set; }

        public virtual string EntityTypeName { get; set; }

        public virtual string InfosetTypeName { get; set; }

        public virtual string ServiceTypeName { get; set; }

        public virtual string EntityName { get; set; }

        public virtual string LabelUri { get; set; }

        public virtual string EntityCanonicalLabel { get; set; }

        public virtual string EntityPrincipalTag { get; set; }

        public virtual string? LabelUrl { get; set; }

        public virtual byte HasIndex { get; set; }

        public virtual byte HasPriority { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual bool IsGenerating { get; set; }

        public Guid? ManagedByAgentGuid { get; set; }

        public string? ManagedByAgentAlias { get; set; }

        public Guid? AuthoredByAgentGuid { get; set; }

        public string? AuthoredByAgentAlias { get; set; }

        public Guid? ReviewedByAgentGuid { get; set; }

        public Guid? EditedByAgentGuid { get; set; }

        public string? EditedByAgentAlias { get; set; }

        public virtual bool IsMarked { get; set; }

        public Guid? CreatedByAgentGuid { get; set; }

        public string? ReviewedByAgentAlias { get; set; }

        public string? CreatedByAgentAlias { get; set; }

        public Guid? UpdatedByAgentGuid { get; set; }

        public string? UpdatedByAgentAlias { get; set; }

        public Guid? DeletedByAgentGuid { get; set; }

        public string? DeletedByAgentAlias { get; set; }

        public virtual DateTime? CreatedOn { get; set; }

        public virtual DateTime? UpdatedOn { get; set; }

        public virtual DateTime? DeletedOn { get; set; }

        public virtual bool IsResolvable { get; set; }

        public virtual bool IsPrincipal { get; set; }

        public virtual bool IsPrivate { get; set; }

        public virtual CoreResrepLeaf CoreResrepLeaf { get; set; }

        public virtual CoreResrepRoot CoreResrepRoot { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
