//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreServiceDefault {

        public Guid ServiceIGuid { get; set; }

        public string ServiceName { get; set; }

        public string ServiceNature { get; set; }

        public Guid ServiceRGuid { get; set; }

        public short ServiceTCode { get; set; }

        public string ServiceTName { get; set; }

        public string ServicePTag { get; set; }

        public Guid DefDiristryGuid { get; set; }

        public Guid DefRegistryGuid { get; set; }

        public Guid DefDirectoryGuid { get; set; }

        public Guid DefRegistrarGuid { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
