//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PDP.DREAM.CoreDataLib.Stores
{

    public partial class CoreDbsqlContext : PDP.DREAM.CoreDataLib.Stores.PdpDbsqlContextBase
    {


        public virtual DbSet<CoreEntityTypeItem> CoreEntityTypeItems
        {
            get;
            set;
        }

        public virtual DbSet<CoreInfosetStatusItem> CoreInfosetStatusItems
        {
            get;
            set;
        }

        public virtual DbSet<CoreServiceTypeItem> CoreServiceTypeItems
        {
            get;
            set;
        }

        public virtual DbSet<CoreInfosetTypeItem> CoreInfosetTypeItems
        {
            get;
            set;
        }

        public virtual DbSet<CoreFieldFormatItem> CoreFieldFormatItems
        {
            get;
            set;
        }

        public virtual DbSet<CoreServiceRestrictionAnd> CoreServiceRestrictionAnds
        {
            get;
            set;
        }

        public virtual DbSet<CoreServiceRestrictionOr> CoreServiceRestrictionOrs
        {
            get;
            set;
        }

        public virtual DbSet<PortalCrossReference> PortalCrossReferences
        {
            get;
            set;
        }

        public virtual DbSet<DoorsDescription> DoorsDescriptions
        {
            get;
            set;
        }

        public virtual DbSet<DoorsDistribution> DoorsDistributions
        {
            get;
            set;
        }

        public virtual DbSet<DoorsLocation> DoorsLocations
        {
            get;
            set;
        }

        public virtual DbSet<PortalOtherText> PortalOtherTexts
        {
            get;
            set;
        }

        public virtual DbSet<DoorsProvenance> DoorsProvenances
        {
            get;
            set;
        }

        public virtual DbSet<PortalSupportingLabel> PortalSupportingLabels
        {
            get;
            set;
        }

        public virtual DbSet<PortalSupportingTag> PortalSupportingTags
        {
            get;
            set;
        }

        public virtual DbSet<DoorsFairMetric> DoorsFairMetrics
        {
            get;
            set;
        }

        public virtual DbSet<CoreEntityLabel> CoreEntityLabels
        {
            get;
            set;
        }

        public virtual DbSet<CoreEntityCanonicalLabel> CoreEntityCanonicalLabels
        {
            get;
            set;
        }

        public virtual DbSet<CoreEntityAliasLabel> CoreEntityAliasLabels
        {
            get;
            set;
        }

        public virtual DbSet<CoreResrepLeaf> CoreResrepLeafs
        {
            get;
            set;
        }

        public virtual DbSet<CoreAccessRequest> CoreAccessRequests
        {
            get;
            set;
        }

        public virtual DbSet<CoreAccessAudit> CoreAccessAudits
        {
            get;
            set;
        }

        public virtual DbSet<CoreResrepRoot> CoreResrepRoots
        {
            get;
            set;
        }

        public virtual DbSet<CoreAccessConnect> CoreAccessConnects
        {
            get;
            set;
        }

        public virtual DbSet<DoorsProvenanceExtn> DoorsProvenanceExtns
        {
            get;
            set;
        }

        public virtual DbSet<DoorsLocationExtn> DoorsLocationExtns
        {
            get;
            set;
        }

        public virtual DbSet<DoorsDistributionExtn> DoorsDistributionExtns
        {
            get;
            set;
        }

        public virtual DbSet<DoorsDescriptionExtn> DoorsDescriptionExtns
        {
            get;
            set;
        }

        public virtual DbSet<CoreResrepSnapshot> CoreResrepSnapshots
        {
            get;
            set;
        }

        public virtual DbSet<CoreResrepService> CoreResrepServices
        {
            get;
            set;
        }

        public virtual DbSet<CoreServiceDefault> CoreServiceDefaults
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration<CoreEntityTypeItem>(new CoreEntityTypeItemConfiguration());
            modelBuilder.ApplyConfiguration<CoreInfosetStatusItem>(new CoreInfosetStatusItemConfiguration());
            modelBuilder.ApplyConfiguration<CoreServiceTypeItem>(new CoreServiceTypeItemConfiguration());
            modelBuilder.ApplyConfiguration<CoreInfosetTypeItem>(new CoreInfosetTypeItemConfiguration());
            modelBuilder.ApplyConfiguration<CoreFieldFormatItem>(new CoreFieldFormatItemConfiguration());
            modelBuilder.ApplyConfiguration<CoreServiceRestrictionAnd>(new CoreServiceRestrictionAndConfiguration());
            modelBuilder.ApplyConfiguration<CoreServiceRestrictionOr>(new CoreServiceRestrictionOrConfiguration());
            modelBuilder.ApplyConfiguration<PortalCrossReference>(new PortalCrossReferenceConfiguration());
            modelBuilder.ApplyConfiguration<DoorsDescription>(new DoorsDescriptionConfiguration());
            modelBuilder.ApplyConfiguration<DoorsDistribution>(new DoorsDistributionConfiguration());
            modelBuilder.ApplyConfiguration<DoorsLocation>(new DoorsLocationConfiguration());
            modelBuilder.ApplyConfiguration<PortalOtherText>(new PortalOtherTextConfiguration());
            modelBuilder.ApplyConfiguration<DoorsProvenance>(new DoorsProvenanceConfiguration());
            modelBuilder.ApplyConfiguration<PortalSupportingLabel>(new PortalSupportingLabelConfiguration());
            modelBuilder.ApplyConfiguration<PortalSupportingTag>(new PortalSupportingTagConfiguration());
            modelBuilder.ApplyConfiguration<DoorsFairMetric>(new DoorsFairMetricConfiguration());
            modelBuilder.ApplyConfiguration<CoreEntityLabel>(new CoreEntityLabelConfiguration());
            modelBuilder.ApplyConfiguration<CoreEntityCanonicalLabel>(new CoreEntityCanonicalLabelConfiguration());
            modelBuilder.ApplyConfiguration<CoreEntityAliasLabel>(new CoreEntityAliasLabelConfiguration());
            modelBuilder.ApplyConfiguration<CoreResrepLeaf>(new CoreResrepLeafConfiguration());
            modelBuilder.ApplyConfiguration<CoreAccessRequest>(new CoreAccessRequestConfiguration());
            modelBuilder.ApplyConfiguration<CoreAccessAudit>(new CoreAccessAuditConfiguration());
            modelBuilder.ApplyConfiguration<CoreResrepRoot>(new CoreResrepRootConfiguration());
            modelBuilder.ApplyConfiguration<CoreAccessConnect>(new CoreAccessConnectConfiguration());
            modelBuilder.ApplyConfiguration<DoorsProvenanceExtn>(new DoorsProvenanceExtnConfiguration());
            modelBuilder.ApplyConfiguration<DoorsLocationExtn>(new DoorsLocationExtnConfiguration());
            modelBuilder.ApplyConfiguration<DoorsDistributionExtn>(new DoorsDistributionExtnConfiguration());
            modelBuilder.ApplyConfiguration<DoorsDescriptionExtn>(new DoorsDescriptionExtnConfiguration());
            modelBuilder.ApplyConfiguration<CoreResrepSnapshot>(new CoreResrepSnapshotConfiguration());
            modelBuilder.ApplyConfiguration<CoreResrepService>(new CoreResrepServiceConfiguration());
            modelBuilder.ApplyConfiguration<CoreServiceDefault>(new CoreServiceDefaultConfiguration());
            CustomizeMapping(ref modelBuilder);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
