//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [Serializable()]
    public partial class CoreAccessRequest {

        public Guid FgroupGuid { get; set; }

        public string RecordHandle { get; set; }

        public string EntityName { get; set; }

        public Guid RecordGuid { get; set; }

        public Guid? AuthoredByAgentGuid { get; set; }

        public string? AuthoredByAgentAlias { get; set; }

        public Guid? EditedByAgentGuid { get; set; }

        public string? EditedByAgentAlias { get; set; }

        public Guid? ManagedByAgentGuid { get; set; }

        public string? ManagedByAgentAlias { get; set; }

        public Guid? ReviewedByAgentGuid { get; set; }

        public string? ReviewedByAgentAlias { get; set; }

        public Guid InfosetGuid { get; set; }

        public Guid? RequestedForAgentGuid { get; set; }

        public string? RequestedForAgentAlias { get; set; }

        public Guid? AllowedByAgentGuid { get; set; }

        public string? AllowedByAgentAlias { get; set; }

        public Guid? DeniedByAgentGuid { get; set; }

        public string? DeniedByAgentAlias { get; set; }

        public Guid? AccessGuid { get; set; }

        public bool AccessAsAuthor { get; set; }

        public bool AccessAsReviewer { get; set; }

        public bool AccessAsEditor { get; set; }

        public bool AccessForService { get; set; }

        public bool AccessIsAllowed { get; set; }

        public bool AccessIsDenied { get; set; }

        public DateTime? CreatedOn { get; set; }

        public Guid? CreatedByAgentGuid { get; set; }

        public string? CreatedByAgentAlias { get; set; }

        public DateTime? DeletedOn { get; set; }

        public Guid? DeletedByAgentGuid { get; set; }

        public string? DeletedByAgentAlias { get; set; }

        public DateTime? UpdatedOn { get; set; }

        public string? UpdatedByAgentAlias { get; set; }

        public Guid? UpdatedByAgentGuid { get; set; }

        public bool? AuthorHasResrepAccess { get; set; }

        public bool? ReviewerHasResrepAccess { get; set; }

        public bool? EditorHasResrepAccess { get; set; }

        public bool? AuthorHasServiceAccess { get; set; }

        public bool? ReviewerHasServiceAccess { get; set; }

        public bool? EditorHasServiceAccess { get; set; }

        public byte HasIndex { get; set; }

        public bool IsDeleted { get; set; }

        public virtual CoreResrepRoot CoreResrepRoot { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
