//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/26/2024 1:02:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.CoreDataLib.Stores
{
    /// <summary>
    /// There are no comments for CoreResrepRootConfiguration in the schema.
    /// </summary>
    public partial class CoreResrepRootConfiguration : IEntityTypeConfiguration<CoreResrepRoot>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CoreResrepRoot> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CoreResrepRoot> builder)
        {
            builder.ToTable(@"CoreResrepRoot", @"dbo");
            builder.Property(x => x.RecordGuid).HasColumnName(@"RecordGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeCode).HasColumnName(@"EntityTypeCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.EntityTypeName).HasColumnName(@"EntityTypeName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.EntityTypeIsComponent).HasColumnName(@"EntityTypeIsComponent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeIsConstituent).HasColumnName(@"EntityTypeIsConstituent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAgent).HasColumnName(@"EntityTypeEditedByAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAuthor).HasColumnName(@"EntityTypeEditedByAuthor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByReviewer).HasColumnName(@"EntityTypeEditedByReviewer").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByEditor).HasColumnName(@"EntityTypeEditedByEditor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAdmin).HasColumnName(@"EntityTypeEditedByAdmin").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityNature).HasColumnName(@"EntityNature").HasColumnType(@"nvarchar(1024)").IsRequired().ValueGeneratedNever().HasMaxLength(1024);
            builder.Property(x => x.EntityInitialPrincipalTag).HasColumnName(@"EntityInitialPrincipalTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityInitialSupportingTag).HasColumnName(@"EntityInitialSupportingTag").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityPrincipalTag).HasColumnName(@"EntityPrincipalTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityCanonicalLabel).HasColumnName(@"EntityCanonicalLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordHandle).HasColumnName(@"RecordHandle").HasColumnType(@"nchar(9)").IsRequired().ValueGeneratedNever().HasMaxLength(9);
            builder.Property(x => x.RecordDiristryGuid).HasColumnName(@"RecordDiristryGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDiristryTag).HasColumnName(@"RecordDiristryTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistryGuid).HasColumnName(@"RecordRegistryGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistryTag).HasColumnName(@"RecordRegistryTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDirectoryGuid).HasColumnName(@"RecordDirectoryGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordArchivedByAgentGuid).HasColumnName(@"RecordArchivedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordArchivedByAgentAlias).HasColumnName(@"RecordArchivedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDirectoryTag).HasColumnName(@"RecordDirectoryTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistrarGuid).HasColumnName(@"RecordRegistrarGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarTag).HasColumnName(@"RecordRegistrarTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordCachedOn).HasColumnName(@"RecordCachedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordCachedByAgentGuid).HasColumnName(@"RecordCachedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordCachedByAgentAlias).HasColumnName(@"RecordCachedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordCreatedOn).HasColumnName(@"RecordCreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordCreatedByAgentGuid).HasColumnName(@"RecordCreatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordIsCached).HasColumnName(@"RecordIsCached").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordCreatedByAgentAlias).HasColumnName(@"RecordCreatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordUpdatedOn).HasColumnName(@"RecordUpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordUpdatedByAgentGuid).HasColumnName(@"RecordUpdatedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordUpdatedByAgentAlias).HasColumnName(@"RecordUpdatedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDeletedOn).HasColumnName(@"RecordDeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedByAgentGuid).HasColumnName(@"RecordDeletedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordIsDeleted).HasColumnName(@"RecordIsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedByAgentAlias).HasColumnName(@"RecordDeletedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordAuthoredByAgentGuid).HasColumnName(@"RecordAuthoredByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordAuthoredByAgentAlias).HasColumnName(@"RecordAuthoredByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordReviewedByAgentGuid).HasColumnName(@"RecordReviewedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordReviewedByAgentAlias).HasColumnName(@"RecordReviewedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordEditedByAgentGuid).HasColumnName(@"RecordEditedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordEditedByAgentAlias).HasColumnName(@"RecordEditedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordManagedByAgentGuid).HasColumnName(@"RecordManagedByAgentGuid").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordManagedByAgentAlias).HasColumnName(@"RecordManagedByAgentAlias").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.InfosetGuid).HasColumnName(@"InfosetGuid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAuthorPrivate).HasColumnName(@"InfosetIsAuthorPrivate").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAgentShared).HasColumnName(@"InfosetIsAgentShared").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsUpdaterLimited).HasColumnName(@"InfosetIsUpdaterLimited").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsManagerReleased).HasColumnName(@"InfosetIsManagerReleased").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusTestedOn).HasColumnName(@"InfosetPortalStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusCode).HasColumnName(@"InfosetPortalStatusCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetPortalStatusName).HasColumnName(@"InfosetPortalStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetDoorsStatusTestedOn).HasColumnName(@"InfosetDoorsStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetDoorsStatusCode).HasColumnName(@"InfosetDoorsStatusCode").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDoorsStatusName).HasColumnName(@"InfosetDoorsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.HasKey(@"RecordGuid");
            builder.HasMany(x => x.CoreEntityLabels).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreEntityAliasLabels).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreEntityCanonicalLabels).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.PortalSupportingTags).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.PortalSupportingLabels).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.PortalCrossReferences).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.PortalOtherTexts).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.DoorsLocations).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.DoorsDescriptions).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.DoorsProvenances).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.DoorsDistributions).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.DoorsFairMetrics).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreAccessRequests).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreEntityTypeItems).WithOne(op => op.CoreResrepRoot).HasPrincipalKey(@"EntityTypeCode").HasForeignKey(@"CodeKey").IsRequired(true);
            builder.HasMany(x => x.CoreServiceRestrictionAnds).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreResrepServices).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);
            builder.HasMany(x => x.CoreResrepSnapshots).WithOne(op => op.CoreResrepRoot).HasForeignKey(@"RecordGuid").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CoreResrepRoot> builder);

        #endregion
    }

}
