<Project Sdk="Microsoft.NET.Sdk.Razor">

  <!-- project declaration -->
  <PropertyGroup>
    <AssemblyName>PDP.DREAM.NexusWebLib</AssemblyName>
    <RootNamespace>PDP.DREAM.NexusWebLib</RootNamespace>
    <Description>PDP-DREAM NexusWebLib</Description>
    <IsPackable>true</IsPackable>
    <Platforms>x64;ARM64;AnyCPU;</Platforms>
  </PropertyGroup>

  <!-- dev/test/build/debug configuration -->
  <PropertyGroup>
    <NoWarn>CS0219;CS8032;CS8600;CS8601;CS8602;CS8603;CS8604;CS8625;IDE0047;IDE0059;NU1902;NU1903;</NoWarn>
  </PropertyGroup>

  <!-- required lib references -->
  <ItemGroup>
  </ItemGroup>

  <!-- required references -->
  <ItemGroup>
    <ProjectReference Include="..\PDP.DREAM.CoreWebLib\PDP.DREAM.CoreWebLib.csproj" />
  </ItemGroup>

</Project>

