//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/17/2023 11:00:38 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.NexusDataLib.Stores
{
    /// <summary>
    /// There are no comments for NexusResrepLeafConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class NexusResrepLeafConfiguration : IEntityTypeConfiguration<NexusResrepLeaf>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<NexusResrepLeaf> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<NexusResrepLeaf> builder)
        {
            builder.ToTable(@"NexusResrepLeaf", @"dbo");
            builder.Property(x => x.RecordGuidKey).HasColumnName(@"RecordGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeCodeRef).HasColumnName(@"EntityTypeCodeRef").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.EntityTypeName).HasColumnName(@"EntityTypeName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.EntityTypeIsComponent).HasColumnName(@"EntityTypeIsComponent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeIsConstituent).HasColumnName(@"EntityTypeIsConstituent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAgent).HasColumnName(@"EntityTypeEditedByAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAuthor).HasColumnName(@"EntityTypeEditedByAuthor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByEditor).HasColumnName(@"EntityTypeEditedByEditor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAdmin).HasColumnName(@"EntityTypeEditedByAdmin").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityInitialTag).HasColumnName(@"EntityInitialTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityNature).HasColumnName(@"EntityNature").HasColumnType(@"nvarchar(1024)").IsRequired().ValueGeneratedNever().HasMaxLength(1024);
            builder.Property(x => x.EntityPrincipalTag).HasColumnName(@"EntityPrincipalTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOtherGuidRef).HasColumnName(@"EntityOtherGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityOtherName).HasColumnName(@"EntityOtherName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOtherTag).HasColumnName(@"EntityOtherTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOtherLabel).HasColumnName(@"EntityOtherLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOwnerGuidRef).HasColumnName(@"EntityOwnerGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityOwnerName).HasColumnName(@"EntityOwnerName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOwnerTag).HasColumnName(@"EntityOwnerTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOwnerLabel).HasColumnName(@"EntityOwnerLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityContactGuidRef).HasColumnName(@"EntityContactGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityContactName).HasColumnName(@"EntityContactName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityContactTag).HasColumnName(@"EntityContactTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityContactLabel).HasColumnName(@"EntityContactLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistrantGuidRef).HasColumnName(@"RecordRegistrantGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrantName).HasColumnName(@"RecordRegistrantName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistrantTag).HasColumnName(@"RecordRegistrantTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistrantLabel).HasColumnName(@"RecordRegistrantLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityCanonicalLabel).HasColumnName(@"EntityCanonicalLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordHandle).HasColumnName(@"RecordHandle").HasColumnType(@"char(9)").IsRequired().ValueGeneratedNever().HasMaxLength(9);
            builder.Property(x => x.RecordSignature).HasColumnName(@"RecordSignature").HasColumnType(@"xml").ValueGeneratedNever();
            builder.Property(x => x.RecordIsCached).HasColumnName(@"RecordIsCached").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordCachedOn).HasColumnName(@"RecordCachedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordDiristryName).HasColumnName(@"RecordDiristryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordIsDeleted).HasColumnName(@"RecordIsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDiristryLabel).HasColumnName(@"RecordDiristryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordArchivedOn).HasColumnName(@"RecordArchivedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistryName).HasColumnName(@"RecordRegistryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDiristryGuidRef).HasColumnName(@"RecordDiristryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistryLabel).HasColumnName(@"RecordRegistryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDiristryTag).HasColumnName(@"RecordDiristryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDirectoryName).HasColumnName(@"RecordDirectoryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistryGuidRef).HasColumnName(@"RecordRegistryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDirectoryLabel).HasColumnName(@"RecordDirectoryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistryTag).HasColumnName(@"RecordRegistryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistrarName).HasColumnName(@"RecordRegistrarName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDirectoryGuidRef).HasColumnName(@"RecordDirectoryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarLabel).HasColumnName(@"RecordRegistrarLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDirectoryTag).HasColumnName(@"RecordDirectoryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistrarGuidRef).HasColumnName(@"RecordRegistrarGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarTag).HasColumnName(@"RecordRegistrarTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordCreatedByAgentGuidRef).HasColumnName(@"RecordCreatedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordCreatedOn).HasColumnName(@"RecordCreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordCreatedByUserName).HasColumnName(@"RecordCreatedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordUpdatedByAgentGuidRef).HasColumnName(@"RecordUpdatedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordUpdatedOn).HasColumnName(@"RecordUpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordUpdatedByUserName).HasColumnName(@"RecordUpdatedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDeletedByAgentGuidRef).HasColumnName(@"RecordDeletedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedOn).HasColumnName(@"RecordDeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedByUserName).HasColumnName(@"RecordDeletedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordManagedByAgentGuidRef).HasColumnName(@"RecordManagedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordManagedByUserName).HasColumnName(@"RecordManagedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.InfosetGuidKey).HasColumnName(@"InfosetGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetEntailment).HasColumnName(@"InfosetEntailment").HasColumnType(@"xml").ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAuthorPrivate).HasColumnName(@"InfosetIsAuthorPrivate").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAgentShared).HasColumnName(@"InfosetIsAgentShared").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsUpdaterLimited).HasColumnName(@"InfosetIsUpdaterLimited").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsManagerReleased).HasColumnName(@"InfosetIsManagerReleased").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusTestedOn).HasColumnName(@"InfosetPortalStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusCode).HasColumnName(@"InfosetPortalStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetPortalStatusName).HasColumnName(@"InfosetPortalStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetDoorsStatusTestedOn).HasColumnName(@"InfosetDoorsStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetDoorsStatusCode).HasColumnName(@"InfosetDoorsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDoorsStatusName).HasColumnName(@"InfosetDoorsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetResrepEntityTestedOn).HasColumnName(@"InfosetResrepEntityTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetResrepEntityStatusCode).HasColumnName(@"InfosetResrepEntityStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetResrepEntityStatusName).HasColumnName(@"InfosetResrepEntityStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetResrepRecordTestedOn).HasColumnName(@"InfosetResrepRecordTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetResrepRecordStatusCode).HasColumnName(@"InfosetResrepRecordStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetResrepRecordStatusName).HasColumnName(@"InfosetResrepRecordStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetResrepInfosetTestedOn).HasColumnName(@"InfosetResrepInfosetTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetResrepInfosetStatusCode).HasColumnName(@"InfosetResrepInfosetStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetResrepInfosetStatusName).HasColumnName(@"InfosetResrepInfosetStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetEntityLabelsCount).HasColumnName(@"InfosetEntityLabelsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetEntityLabelsStatusCode).HasColumnName(@"InfosetEntityLabelsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetEntityLabelsStatusName).HasColumnName(@"InfosetEntityLabelsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetSupportingTagsCount).HasColumnName(@"InfosetSupportingTagsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetSupportingTagsStatusCode).HasColumnName(@"InfosetSupportingTagsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetSupportingTagsStatusName).HasColumnName(@"InfosetSupportingTagsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetSupportingLabelsCount).HasColumnName(@"InfosetSupportingLabelsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetSupportingLabelsStatusCode).HasColumnName(@"InfosetSupportingLabelsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetSupportingLabelsStatusName).HasColumnName(@"InfosetSupportingLabelsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetCrossReferencesCount).HasColumnName(@"InfosetCrossReferencesCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetCrossReferencesStatusCode).HasColumnName(@"InfosetCrossReferencesStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetCrossReferencesStatusName).HasColumnName(@"InfosetCrossReferencesStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetOtherTextsCount).HasColumnName(@"InfosetOtherTextsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetOtherTextsStatusCode).HasColumnName(@"InfosetOtherTextsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetOtherTextsStatusName).HasColumnName(@"InfosetOtherTextsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetLocationsCount).HasColumnName(@"InfosetLocationsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetLocationsStatusCode).HasColumnName(@"InfosetLocationsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetLocationsStatusName).HasColumnName(@"InfosetLocationsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetDescriptionsCount).HasColumnName(@"InfosetDescriptionsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDescriptionsStatusCode).HasColumnName(@"InfosetDescriptionsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDescriptionsStatusName).HasColumnName(@"InfosetDescriptionsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetProvenancesCount).HasColumnName(@"InfosetProvenancesCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetProvenancesStatusCode).HasColumnName(@"InfosetProvenancesStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetProvenancesStatusName).HasColumnName(@"InfosetProvenancesStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetDistributionsCount).HasColumnName(@"InfosetDistributionsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDistributionsStatusCode).HasColumnName(@"InfosetDistributionsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDistributionsStatusName).HasColumnName(@"InfosetDistributionsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetFairMetricsCount).HasColumnName(@"InfosetFairMetricsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetFairMetricsStatusCode).HasColumnName(@"InfosetFairMetricsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetFairMetricsStatusName).HasColumnName(@"InfosetFairMetricsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetNexusSnapshotsCount).HasColumnName(@"InfosetNexusSnapshotsCount").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetNexusSnapshotsStatusCode).HasColumnName(@"InfosetNexusSnapshotsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetNexusSnapshotsStatusName).HasColumnName(@"InfosetNexusSnapshotsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.HasKey(@"RecordGuidKey");
            builder.HasMany(x => x.NexusEntityLabels).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusSupportingTags).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusSupportingLabels).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusCrossReferences).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusOtherTexts).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusLocations).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusDescriptions).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusDistributions).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusProvenances).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusFairMetrics).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusEntityAliasLabels).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusEntityCanonicalLabels).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusServiceRestrictionAnds).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusNexusSnapshots).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusCoreServiceDefaults).WithOne(op => op.NexusResrepLeaf).HasForeignKey(@"RecordGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<NexusResrepLeaf> builder);

        #endregion
    }

}
