//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/12/2022 2:20:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PDP.DREAM.NexusDataLib.Stores
{
    /// <summary>
    /// There are no comments for NexusResrepStemConfiguration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class NexusResrepStemConfiguration : IEntityTypeConfiguration<NexusResrepStem>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<NexusResrepStem> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<NexusResrepStem> builder)
        {
            builder.ToTable(@"NexusResrepStem", @"dbo");
            builder.Property(x => x.RecordGuidKey).HasColumnName(@"RecordGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeName).HasColumnName(@"EntityTypeName").HasColumnType(@"nvarchar(32)").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.EntityTypeCodeRef).HasColumnName(@"EntityTypeCodeRef").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.EntityTypeIsComponent).HasColumnName(@"EntityTypeIsComponent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeIsConstituent).HasColumnName(@"EntityTypeIsConstituent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAgent).HasColumnName(@"EntityTypeEditedByAgent").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAuthor).HasColumnName(@"EntityTypeEditedByAuthor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByEditor).HasColumnName(@"EntityTypeEditedByEditor").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityTypeEditedByAdmin).HasColumnName(@"EntityTypeEditedByAdmin").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityInitialTag).HasColumnName(@"EntityInitialTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityPrincipalTag).HasColumnName(@"EntityPrincipalTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOtherGuidRef).HasColumnName(@"EntityOtherGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityOtherName).HasColumnName(@"EntityOtherName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOtherTag).HasColumnName(@"EntityOtherTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOtherLabel).HasColumnName(@"EntityOtherLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOwnerGuidRef).HasColumnName(@"EntityOwnerGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityOwnerName).HasColumnName(@"EntityOwnerName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityOwnerTag).HasColumnName(@"EntityOwnerTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityOwnerLabel).HasColumnName(@"EntityOwnerLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityContactGuidRef).HasColumnName(@"EntityContactGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.EntityContactName).HasColumnName(@"EntityContactName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityContactTag).HasColumnName(@"EntityContactTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.EntityContactLabel).HasColumnName(@"EntityContactLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistrantGuidRef).HasColumnName(@"RecordRegistrantGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrantName).HasColumnName(@"RecordRegistrantName").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistrantTag).HasColumnName(@"RecordRegistrantTag").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistrantLabel).HasColumnName(@"RecordRegistrantLabel").HasColumnType(@"nvarchar(256)").ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.EntityNature).HasColumnName(@"EntityNature").HasColumnType(@"nvarchar(1024)").IsRequired().ValueGeneratedNever().HasMaxLength(1024);
            builder.Property(x => x.EntityCanonicalLabel).HasColumnName(@"EntityCanonicalLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordHandle).HasColumnName(@"RecordHandle").HasColumnType(@"char(9)").IsRequired().ValueGeneratedNever().HasMaxLength(9);
            builder.Property(x => x.RecordIsCached).HasColumnName(@"RecordIsCached").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordCachedOn).HasColumnName(@"RecordCachedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordIsDeleted).HasColumnName(@"RecordIsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordArchivedOn).HasColumnName(@"RecordArchivedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarGuidRef).HasColumnName(@"RecordRegistrarGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarTag).HasColumnName(@"RecordRegistrarTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDiristryGuidRef).HasColumnName(@"RecordDiristryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDiristryName).HasColumnName(@"RecordDiristryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDiristryTag).HasColumnName(@"RecordDiristryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDiristryLabel).HasColumnName(@"RecordDiristryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistryGuidRef).HasColumnName(@"RecordRegistryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordRegistryName).HasColumnName(@"RecordRegistryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordRegistryTag).HasColumnName(@"RecordRegistryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordRegistryLabel).HasColumnName(@"RecordRegistryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDirectoryGuidRef).HasColumnName(@"RecordDirectoryGuidRef").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RecordDirectoryName).HasColumnName(@"RecordDirectoryName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordDirectoryTag).HasColumnName(@"RecordDirectoryTag").HasColumnType(@"nvarchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDirectoryLabel).HasColumnName(@"RecordDirectoryLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordCreatedByAgentGuidRef).HasColumnName(@"RecordCreatedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarName).HasColumnName(@"RecordRegistrarName").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordCreatedOn).HasColumnName(@"RecordCreatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordRegistrarLabel).HasColumnName(@"RecordRegistrarLabel").HasColumnType(@"nvarchar(256)").IsRequired().ValueGeneratedNever().HasMaxLength(256);
            builder.Property(x => x.RecordUpdatedByAgentGuidRef).HasColumnName(@"RecordUpdatedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordUpdatedOn).HasColumnName(@"RecordUpdatedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedByAgentGuidRef).HasColumnName(@"RecordDeletedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordDeletedOn).HasColumnName(@"RecordDeletedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.RecordCreatedByUserName).HasColumnName(@"RecordCreatedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordUpdatedByUserName).HasColumnName(@"RecordUpdatedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordDeletedByUserName).HasColumnName(@"RecordDeletedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordManagedByAgentGuidRef).HasColumnName(@"RecordManagedByAgentGuidRef").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.RecordManagedByUserName).HasColumnName(@"RecordManagedByUserName").HasColumnType(@"nvarchar(64)").ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.RecordSignature).HasColumnName(@"RecordSignature").HasColumnType(@"xml").ValueGeneratedNever();
            builder.Property(x => x.InfosetGuidKey).HasColumnName(@"InfosetGuidKey").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAuthorPrivate).HasColumnName(@"InfosetIsAuthorPrivate").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsAgentShared).HasColumnName(@"InfosetIsAgentShared").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsUpdaterLimited).HasColumnName(@"InfosetIsUpdaterLimited").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetIsManagerReleased).HasColumnName(@"InfosetIsManagerReleased").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InfosetEntailment).HasColumnName(@"InfosetEntailment").HasColumnType(@"xml").ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusTestedOn).HasColumnName(@"InfosetPortalStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetPortalStatusCode).HasColumnName(@"InfosetPortalStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetPortalStatusName).HasColumnName(@"InfosetPortalStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.InfosetDoorsStatusTestedOn).HasColumnName(@"InfosetDoorsStatusTestedOn").HasColumnType(@"datetime2").ValueGeneratedNever();
            builder.Property(x => x.InfosetDoorsStatusCode).HasColumnName(@"InfosetDoorsStatusCode").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0);
            builder.Property(x => x.InfosetDoorsStatusName).HasColumnName(@"InfosetDoorsStatusName").HasColumnType(@"nvarchar(32)").ValueGeneratedNever().HasMaxLength(32);
            builder.HasKey(@"RecordGuidKey");
            builder.HasMany(x => x.NexusEntityLabels).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusSupportingTags).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusSupportingLabels).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusCrossReferences).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusOtherTexts).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusEntityCanonicalLabels).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusEntityAliasLabels).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusLocations).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusDescriptions).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusProvenances).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusDistributions).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusFairMetrics).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusServiceRestrictionAnds).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusNexusSnapshots).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);
            builder.HasMany(x => x.NexusServiceCoreDefaults).WithOne(op => op.NexusResrepStem).HasForeignKey(@"RecordGuidRef").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<NexusResrepStem> builder);

        #endregion
    }

}
