<Project Sdk="Microsoft.NET.Sdk.Razor">

  <!-- project declaration -->
  <PropertyGroup>
    <AssemblyName>PDP.DREAM.CoreWebLib</AssemblyName>
    <RootNamespace>PDP.DREAM.CoreWebLib</RootNamespace>
    <Description>PDP-DREAM CoreWebLib</Description>
    <Authors>Carl Taswell and the PORTAL-DOORS Project Team</Authors>
    <Company>Brain Health Alliance</Company>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!-- dev/test/build/debug configuration -->
  <PropertyGroup>
    <NoWarn>CS0168;CS0219;CS8032;CS8070;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8620;CS8622;CS8629;CS8765;CS8767;IDE0047;IDE0059;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PDP.DREAM.CoreDataLib\PDP.DREAM.CoreDataLib.csproj" />
  </ItemGroup>

  <!-- required lib references -->

  <!-- required PDP references -->

</Project>

