//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021-07-11 07:51:08
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.SiaaDataLib.Stores.PdpIdentity
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class QebIdentityAppUserRole {

        public QebIdentityAppUserRole()
        {
            OnCreated();
        }

        public virtual Guid LinkGuidKey { get; set; }

        public virtual Guid UserGuidRef { get; set; }

        public virtual string UserName { get; set; }

        public virtual string UserNameDisplayed { get; set; }

        public virtual Guid RoleGuidRef { get; set; }

        public virtual string RoleName { get; set; }

        public virtual string RoleDescription { get; set; }

        public virtual Guid AppGuidRef { get; set; }

        public virtual string AppName { get; set; }

        public virtual string AppDescription { get; set; }

        public virtual string? ConcurrencyStamp { get; set; }

        public virtual QebIdentityAppUser QebIdentityAppUser { get; set; }

        public virtual QebIdentityAppRole QebIdentityAppRole { get; set; }

        public virtual QebIdentityApp QebIdentityApp { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
