//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021-06-27 18:49:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.SiaaDataLib.Stores.PdpIdentity
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class QebIdentityAppUserRoleLink {

        public QebIdentityAppUserRoleLink()
        {
            OnCreated();
        }

        public virtual Guid LinkGuidKey { get; set; }

        public virtual Guid UserGuidRef { get; set; }

        public virtual Guid RoleGuidRef { get; set; }

        public virtual Guid AppGuidRef { get; set; }

        public virtual string? ConcurrencyStamp { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
