// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUserRoleLink
{
    public Guid LinkGuidKey { get; set; }

    public Guid UserGuidRef { get; set; }

    public Guid RoleGuidRef { get; set; }

    public Guid AppGuidRef { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetRole RoleGuidRefNavigation { get; set; }

    public virtual SiaaNetUser UserGuidRefNavigation { get; set; }
}