// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUserLogin
{
    public Guid UserGuidRef { get; set; }

    public Guid LoginGuidKey { get; set; }

    public string LoginProvider { get; set; }

    public string ProviderKey { get; set; }

    public string ProviderNameDisplayed { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetUser UserGuidRefNavigation { get; set; }
}