// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUserSession
{
    public Guid AppGuidRef { get; set; }

    public Guid UserGuidRef { get; set; }

    public Guid? AgentGuidRef { get; set; }

    public Guid SessionGuidKey { get; set; }

    public DateTime? SessionDateCreated { get; set; }

    public DateTime? SessionDateAccessed { get; set; }

    public DateTime? SessionDateExpired { get; set; }

    public string UserNameDisplayed { get; set; }

    public bool UserIsAgent { get; set; }

    public bool AgentIsAuthor { get; set; }

    public bool AgentIsEditor { get; set; }

    public bool AgentIsAdmin { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetUser UserGuidRefNavigation { get; set; }
}