// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUserToken
{
    public Guid TokenGuidKey { get; set; }

    public string LoginProvider { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public Guid UserGuidRef { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetUser UserGuidRefNavigation { get; set; }
}