// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetRoleClaim
{
    public Guid RoleGuidRef { get; set; }

    public Guid ClaimGuidKey { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetRole RoleGuidRefNavigation { get; set; }
}