// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUserClaim
{
    public Guid UserGuidRef { get; set; }

    public Guid ClaimGuidKey { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual SiaaNetUser UserGuidRefNavigation { get; set; }
}