// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PDP.DREAM.CoreDataLib.Models;

public partial class SiaaNetUser
{
    public Guid AppGuidRef { get; set; }

    public Guid AgentGuidRef { get; set; }

    public Guid? SessionGuidRef { get; set; }

    public Guid UserGuidKey { get; set; }

    public int AccessFailedCount { get; set; }

    public string ConcurrencyStamp { get; set; }

    public DateTime? DateEmailConfirmed { get; set; }

    public DateTime? DateLastEdit { get; set; }

    public DateTime? DateLastLockout { get; set; }

    public DateTime? DateLastLogin { get; set; }

    public DateTime? DatePasswordChanged { get; set; }

    public DateTime? DateProfileChanged { get; set; }

    public DateTime? DateTokenExpired { get; set; }

    public DateTime? DateUserCreated { get; set; }

    public DateTime? DateUserNameChanged { get; set; }

    public string EmailAddress { get; set; }

    public string EmailAlternate { get; set; }

    public bool EmailConfirmed { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool LockoutEnabled { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public DateTime? LockoutEndDateUtc { get; set; }

    public string Organization { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public string SecurityAnswer { get; set; }

    public string SecurityQuestion { get; set; }

    public string SecurityStamp { get; set; }

    public string SecurityToken { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public bool UserIsApproved { get; set; }

    public bool UserIsAgent { get; set; }

    public bool AgentIsAuthor { get; set; }

    public bool AgentIsEditor { get; set; }

    public bool AgentIsAdmin { get; set; }

    public string UserName { get; set; }

    public string UserNameDisplayed { get; set; }

    public string WebsiteAddress { get; set; }

    public virtual ICollection<SiaaNetUserClaim> SiaaNetUserClaims { get; } = new List<SiaaNetUserClaim>();

    public virtual ICollection<SiaaNetUserLogin> SiaaNetUserLogins { get; } = new List<SiaaNetUserLogin>();

    public virtual ICollection<SiaaNetUserRoleLink> SiaaNetUserRoleLinks { get; } = new List<SiaaNetUserRoleLink>();

    public virtual ICollection<SiaaNetUserSession> SiaaNetUserSessions { get; } = new List<SiaaNetUserSession>();

    public virtual ICollection<SiaaNetUserToken> SiaaNetUserTokens { get; } = new List<SiaaNetUserToken>();
}