//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/8/2022 4:03:34 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace PDP.DREAM.CoreDataLib.Stores
{
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class QebIdentityAppUser {

        public virtual Guid UserGuidKey { get; set; }

        public virtual Guid? SessionGuidRef { get; set; }

        public virtual Guid AppGuidRef { get; set; }

        public virtual int AccessFailedCount { get; set; }

        public virtual string? ConcurrencyStamp { get; set; }

        public virtual DateTime? DateEmailConfirmed { get; set; }

        public virtual DateTime? DateLastEdit { get; set; }

        public virtual DateTime? DateLastLockout { get; set; }

        public virtual DateTime? DateLastLogin { get; set; }

        public virtual DateTime? DatePasswordChanged { get; set; }

        public virtual DateTime? DateProfileChanged { get; set; }

        public virtual DateTime? DateTokenExpired { get; set; }

        public virtual DateTime? DateUserCreated { get; set; }

        public virtual DateTime? DateUserNameChanged { get; set; }

        public virtual string EmailAddress { get; set; }

        public virtual string EmailAlternate { get; set; }

        public virtual bool EmailConfirmed { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual bool LockoutEnabled { get; set; }

        public virtual DateTimeOffset? LockoutEnd { get; set; }

        public virtual DateTime? LockoutEndDateUtc { get; set; }

        public virtual string Organization { get; set; }

        public virtual string PasswordHash { get; set; }

        public virtual string PhoneNumber { get; set; }

        public virtual bool PhoneNumberConfirmed { get; set; }

        public virtual string SecurityAnswer { get; set; }

        public virtual string SecurityQuestion { get; set; }

        public virtual string SecurityStamp { get; set; }

        public virtual string SecurityToken { get; set; }

        public virtual bool TwoFactorEnabled { get; set; }

        public virtual bool UserIsApproved { get; set; }

        public virtual string UserName { get; set; }

        public virtual string UserNameDisplayed { get; set; }

        public virtual string WebsiteAddress { get; set; }

        public virtual QebIdentityApp QebIdentityApp { get; set; }

        public virtual IList<QebIdentityAppUserRole> QebIdentityAppUserRoles { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
